const dumy = [
  {
    title: "Vicugna vicugna",
    content: "felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar",
    nickname: "Vicuna",
    mainidx: 2,
    subidx: 1,
  },
  {
    title: "Milvus migrans",
    content: "non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis",
    nickname: "Kite, black",
    mainidx: 2,
    subidx: 0,
  },
  {
    title: "Echimys chrysurus",
    content: "aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in",
    nickname: "Rat, white-faced tree",
    mainidx: 1,
    subidx: 0,
  },
  {
    title: "Phoenicopterus chilensis",
    content: "ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna",
    nickname: "Chilean flamingo",
    mainidx: 0,
    subidx: 1,
  },
  {
    title: "Felis chaus",
    content: "lorem quisque ut erat curabitur gravida nisi at nibh in",
    nickname: "Jungle cat",
    mainidx: 0,
    subidx: 0,
  },
  {
    title: "Castor canadensis",
    content: "mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis",
    nickname: "Beaver, north american",
    mainidx: 1,
    subidx: 1,
  },
  {
    title: "Phaethon aethereus",
    content: "condimentum id luctus nec molestie sed justo pellentesque viverra pede",
    nickname: "Red-billed tropic bird",
    mainidx: 2,
    subidx: 0,
  },
  {
    title: "Raphicerus campestris",
    content: "suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla",
    nickname: "Steenbuck",
    mainidx: 1,
    subidx: 1,
  },
  {
    title: "Ovis ammon",
    content: "phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin",
    nickname: "Argalis",
    mainidx: 0,
    subidx: 0,
  },
  {
    title: "Bubalornis niger",
    content: "curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris",
    nickname: "Weaver, red-billed buffalo",
    mainidx: 2,
    subidx: 1,
  },
  {
    title: "Varanus sp.",
    content: "risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante",
    nickname: "Lizard, goanna",
    mainidx: 2,
    subidx: 1,
  },
  {
    title: "unavailable",
    content: "morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem",
    nickname: "Flying fox (unidentified)",
    mainidx: 2,
    subidx: 1,
  },
  {
    title: "Junonia genoveua",
    content: "volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque",
    nickname: "Tropical buckeye butterfly",
    mainidx: 0,
    subidx: 0,
  },
  {
    title: "Trichosurus vulpecula",
    content: "morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla",
    nickname: "Possum, golden brush-tailed",
    mainidx: 0,
    subidx: 0,
  },
  {
    title: "Petaurus norfolcensis",
    content: "sit amet justo morbi ut odio cras mi pede malesuada",
    nickname: "Squirrel glider",
    mainidx: 1,
    subidx: 0,
  },
  {
    title: "Crocuta crocuta",
    content: "in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean",
    nickname: "Spotted hyena",
    mainidx: 2,
    subidx: 0,
  },
  {
    title: "Felis concolor",
    content: "nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta",
    nickname: "Puma, south american",
    mainidx: 2,
    subidx: 0,
  },
  {
    title: "Hippotragus equinus",
    content: "sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam",
    nickname: "Roan antelope",
    mainidx: 0,
    subidx: 1,
  },
  {
    title: "Propithecus verreauxi",
    content: "morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet",
    nickname: "Verreaux's sifaka",
    mainidx: 0,
    subidx: 0,
  },
  {
    title: "Sitta canadensis",
    content: "etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut",
    nickname: "Nuthatch, red-breasted",
    mainidx: 1,
    subidx: 1,
  },
  {
    title: "Ardea golieth",
    content: "vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros",
    nickname: "Heron, giant",
    mainidx: 2,
    subidx: 0,
  },
  {
    title: "Eubalaena australis",
    content: "amet justo morbi ut odio cras mi pede malesuada in",
    nickname: "Baleen Jerry",
    mainidx: 1,
    subidx: 0,
  },
  {
    title: "Corvus albicollis",
    content: "platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam",
    nickname: "Cape raven",
    mainidx: 0,
    subidx: 1,
  },
  {
    title: "Jerry ursinus",
    content: "habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque",
    nickname: "Common wombat",
    mainidx: 1,
    subidx: 1,
  },
  {
    title: "Tachybaptus ruficollis",
    content: "sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel",
    nickname: "Dabchick",
    mainidx: 1,
    subidx: 1,
  },
  {
    title: "Meles meles",
    content: "phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque",
    nickname: "Eurasian badger",
    mainidx: 0,
    subidx: 1,
  },
  {
    title: "Libellula quadrimaculata",
    content: "maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque",
    nickname: "Dragonfly, russian",
    mainidx: 2,
    subidx: 0,
  },
  {
    title: "Phalacrocorax brasilianus",
    content: "aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum",
    nickname: "Neotropic cormorant",
    mainidx: 2,
    subidx: 1,
  },
  {
    title: "Trichoglossus haematodus moluccanus",
    content: "libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas",
    nickname: "Lory, rainbow",
    mainidx: 1,
    subidx: 1,
  },
  {
    title: "Dusicyon thous",
    content: "eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing",
    nickname: "Savanna fox",
    mainidx: 2,
    subidx: 1,
  },
  {
    title: "Ephipplorhynchus senegalensis",
    content: "quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet",
    nickname: "Saddle-billed stork",
    mainidx: 2,
    subidx: 1,
  },
  {
    title: "Vanellus chilensis",
    content: "tincidunt eu felis fusce posuere felis sed lacus morbi sem",
    nickname: "Lapwing, southern",
    mainidx: 0,
    subidx: 0,
  },
  {
    title: "Cynictis penicillata",
    content: "tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum",
    nickname: "Mongoose, yellow",
    mainidx: 0,
    subidx: 1,
  },
  {
    title: "Loris tardigratus",
    content: "odio in hac habitasse platea dictumst maecenas ut massa quis",
    nickname: "Slender loris",
    mainidx: 0,
    subidx: 0,
  },
  {
    title: "Sitta canadensis",
    content: "vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum",
    nickname: "Red-breasted nuthatch",
    mainidx: 0,
    subidx: 1,
  },
  {
    title: "Eudyptula minor",
    content: "phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in",
    nickname: "Penguin, fairy",
    mainidx: 2,
    subidx: 1,
  },
  {
    title: "Paroaria gularis",
    content: "sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis",
    nickname: "Cardinal, red-capped",
    mainidx: 1,
    subidx: 1,
  },
  {
    title: "Cochlearius cochlearius",
    content: "suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas",
    nickname: "Heron, boat-billed",
    mainidx: 2,
    subidx: 1,
  },
  {
    title: "Catharacta skua",
    content: "sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit",
    nickname: "Great skua",
    mainidx: 2,
    subidx: 1,
  },
  {
    title: "Tachybaptus ruficollis",
    content: "nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat",
    nickname: "Dabchick",
    mainidx: 2,
    subidx: 1,
  },
  {
    title: "Marmota monax",
    content: "sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea",
    nickname: "Groundhog",
    mainidx: 2,
    subidx: 0,
  },
  {
    title: "Zosterops pallidus",
    content: "semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id",
    nickname: "Cape white-eye",
    mainidx: 1,
    subidx: 1,
  },
  {
    title: "Spizaetus coronatus",
    content: "praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia",
    nickname: "Eagle, crowned",
    mainidx: 1,
    subidx: 1,
  },
  {
    title: "Egretta thula",
    content: "cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros",
    nickname: "Egret, snowy",
    mainidx: 2,
    subidx: 1,
  },
  {
    title: "Butorides striatus",
    content: "platea dictumst etiam faucibus cursus urna ut tellus nulla ut",
    nickname: "Heron, little",
    mainidx: 2,
    subidx: 0,
  },
  {
    title: "Lamprotornis chalybaeus",
    content: "enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus",
    nickname: "Greater blue-eared starling",
    mainidx: 1,
    subidx: 0,
  },
  {
    title: "Castor fiber",
    content: "nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in",
    nickname: "European beaver",
    mainidx: 0,
    subidx: 1,
  },
  {
    title: "Speothos vanaticus",
    content: "lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus",
    nickname: "Dog, bush",
    mainidx: 0,
    subidx: 0,
  },
  {
    title: "Oxybelis sp.",
    content: "nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor",
    nickname: "Vine snake (unidentified)",
    mainidx: 1,
    subidx: 1,
  },
  {
    title: "Litrocranius walleri",
    content: "vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et",
    nickname: "Gerenuk",
    mainidx: 1,
    subidx: 0,
  },
  {
    title: "Eudyptula minor",
    content: "ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis",
    nickname: "Little blue penguin",
    mainidx: 2,
    subidx: 0,
  },
  {
    title: "Chlidonias leucopterus",
    content: "dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc",
    nickname: "White-winged tern",
    mainidx: 2,
    subidx: 1,
  },
  {
    title: "Castor canadensis",
    content: "lobortis sapien sapien non mi integer ac neque duis bibendum morbi",
    nickname: "Beaver, north american",
    mainidx: 2,
    subidx: 0,
  },
  {
    title: "Antechinus flavipes",
    content: "ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris",
    nickname: "Antechinus, brown",
    mainidx: 2,
    subidx: 0,
  },
  {
    title: "Hystrix cristata",
    content: "nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum",
    nickname: "Crested porcupine",
    mainidx: 0,
    subidx: 0,
  },
  {
    title: "Caiman crocodilus",
    content: "sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec",
    nickname: "Spectacled caiman",
    mainidx: 2,
    subidx: 1,
  },
  {
    title: "Martes pennanti",
    content: "ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae",
    nickname: "Fisher",
    mainidx: 2,
    subidx: 0,
  },
  {
    title: "Terrapene carolina",
    content: "dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi",
    nickname: "Turtle, eastern box",
    mainidx: 2,
    subidx: 1,
  },
  {
    title: "Porphyrio porphyrio",
    content: "tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis",
    nickname: "Moorhen, purple",
    mainidx: 1,
    subidx: 0,
  },
  {
    title: "Sylvilagus floridanus",
    content: "posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec",
    nickname: "Rabbit, eastern cottontail",
    mainidx: 0,
    subidx: 1,
  },
  {
    title: "Ratufa indica",
    content: "sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus",
    nickname: "Malabar squirrel",
    mainidx: 1,
    subidx: 1,
  },
  {
    title: "Ovibos moschatus",
    content: "ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum",
    nickname: "Ox, musk",
    mainidx: 0,
    subidx: 1,
  },
  {
    title: "Spilogale gracilis",
    content: "iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna",
    nickname: "Western spotted skunk",
    mainidx: 1,
    subidx: 0,
  },
  {
    title: "Camelus dromedarius",
    content: "mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus",
    nickname: "Dromedary camel",
    mainidx: 0,
    subidx: 0,
  },
  {
    title: "Funambulus pennati",
    content: "ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut",
    nickname: "Squirrel, palm",
    mainidx: 1,
    subidx: 0,
  },
  {
    title: "Eubalaena australis",
    content: "curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec",
    nickname: "Whale, southern right",
    mainidx: 2,
    subidx: 0,
  },
  {
    title: "Stercorarius longicausus",
    content: "lorem quisque ut erat curabitur gravida nisi at nibh in hac",
    nickname: "Jaeger, long-tailed",
    mainidx: 0,
    subidx: 0,
  },
  {
    title: "Pycnonotus nigricans",
    content: "justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et",
    nickname: "Bulbul, black-fronted",
    mainidx: 0,
    subidx: 1,
  },
  {
    title: "Chauna torquata",
    content: "adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante",
    nickname: "Crested screamer",
    mainidx: 2,
    subidx: 1,
  },
  {
    title: "Dendrohyrax brucel",
    content: "diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales",
    nickname: "Hyrax",
    mainidx: 1,
    subidx: 0,
  },
  {
    title: "Lamprotornis superbus",
    content: "pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam",
    nickname: "Starling, superb",
    mainidx: 2,
    subidx: 1,
  },
  {
    title: "Columba livia",
    content: "faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo",
    nickname: "Feral rock pigeon",
    mainidx: 2,
    subidx: 0,
  },
  {
    title: "Ursus americanus",
    content: "suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id",
    nickname: "Black bear",
    mainidx: 0,
    subidx: 1,
  },
  {
    title: "Tauraco porphyrelophus",
    content: "nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti",
    nickname: "Violet-crested turaco",
    mainidx: 1,
    subidx: 1,
  },
  {
    title: "Otaria flavescens",
    content: "suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus",
    nickname: "Southern sea lion",
    mainidx: 2,
    subidx: 0,
  },
  {
    title: "Phoeniconaias minor",
    content: "bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus",
    nickname: "Lesser flamingo",
    mainidx: 0,
    subidx: 0,
  },
  {
    title: "Neotoma sp.",
    content: "nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt",
    nickname: "Woodrat (unidentified)",
    mainidx: 1,
    subidx: 0,
  },
  {
    title: "Falco peregrinus",
    content: "orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio",
    nickname: "Falcon, peregrine",
    mainidx: 2,
    subidx: 0,
  },
  {
    title: "Neotis denhami",
    content: "luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh",
    nickname: "Stanley bustard",
    mainidx: 0,
    subidx: 0,
  },
  {
    title: "Corvus albicollis",
    content: "sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus",
    nickname: "Raven, white-necked",
    mainidx: 2,
    subidx: 0,
  },
  {
    title: "Chauna torquata",
    content: "ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam",
    nickname: "Crested screamer",
    mainidx: 1,
    subidx: 1,
  },
  {
    title: "Coluber constrictor",
    content: "integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor",
    nickname: "Racer snake",
    mainidx: 2,
    subidx: 1,
  },
  {
    title: "Laniaurius atrococcineus",
    content: "lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer",
    nickname: "Gonolek, burchell's",
    mainidx: 2,
    subidx: 0,
  },
  {
    title: "Sitta canadensis",
    content: "eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio",
    nickname: "Red-breasted nuthatch",
    mainidx: 2,
    subidx: 0,
  },
  {
    title: "Felis yagouaroundi",
    content: "odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam",
    nickname: "Jaguarundi",
    mainidx: 0,
    subidx: 1,
  },
  {
    title: "Connochaetus taurinus",
    content: "sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis",
    nickname: "Brindled gnu",
    mainidx: 0,
    subidx: 1,
  },
  {
    title: "Podargus strigoides",
    content: "ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate",
    nickname: "Tawny frogmouth",
    mainidx: 2,
    subidx: 0,
  },
  {
    title: "Tursiops truncatus",
    content: "duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo",
    nickname: "Dolphin, bottle-nose",
    mainidx: 1,
    subidx: 1,
  },
  {
    title: "Ara ararauna",
    content: "lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse",
    nickname: "Blue and gold macaw",
    mainidx: 0,
    subidx: 1,
  },
  {
    title: "Macropus eugenii",
    content: "convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo",
    nickname: "Dama wallaby",
    mainidx: 1,
    subidx: 0,
  },
  {
    title: "Diomedea irrorata",
    content: "quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in",
    nickname: "Albatross, waved",
    mainidx: 1,
    subidx: 1,
  },
  {
    title: "Ardea golieth",
    content: "turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est",
    nickname: "Goliath heron",
    mainidx: 0,
    subidx: 1,
  },
  {
    title: "Upupa epops",
    content: "vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor",
    nickname: "Hoopoe, eurasian",
    mainidx: 2,
    subidx: 1,
  },
  {
    title: "Callipepla gambelii",
    content: "bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac",
    nickname: "Quail, gambel's",
    mainidx: 0,
    subidx: 1,
  },
  {
    title: "Agkistrodon piscivorus",
    content: "nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu",
    nickname: "Moccasin, water",
    mainidx: 2,
    subidx: 0,
  },
  {
    title: "Mabuya spilogaster",
    content: "et ultrices posuere cubilia curae nulla dapibus dolor vel est donec",
    nickname: "African skink",
    mainidx: 2,
    subidx: 1,
  },
  {
    title: "Hymenolaimus malacorhynchus",
    content: "curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor",
    nickname: "Duck, mountain",
    mainidx: 2,
    subidx: 1,
  },
  {
    title: "Genetta genetta",
    content: "mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta",
    nickname: "Genet, small-spotted",
    mainidx: 2,
    subidx: 1,
  },
  {
    title: "Terrapene carolina",
    content: "sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue",
    nickname: "Eastern box turtle",
    mainidx: 1,
    subidx: 0,
  },
  {
    title: "Dusicyon thous",
    content: "sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in",
    nickname: "Fox, crab-eating",
    mainidx: 0,
    subidx: 0,
  },
];

module.exports = dumy;
