const Boards = [

  {
    userid: "cloudcoke",
    title: "The Lumière Brothers' First Films",
    content: "ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac",
    nickname: "qkrwhdghks123",
    mainidx: 2,
    subidx: 0,
  },
  {
    userid: "web7722",
    title: "Butch and Sundance: The Early Days",
    content: "magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque",
    nickname: "web",
    mainidx: 0,
    subidx: 0,
  },
  {
    userid: "qkrwhdghks",
    title: "Chinese Ghost Story, A (Sinnui yauwan)",
    content: "elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula",
    nickname: "web",
    mainidx: 2,
    subidx: 0,
  },
  {
    userid: "web7722",
    title: "The Disappeared",
    content: "lacus at turpis donec posuere metus vitae ipsum aliquam non",
    nickname: "web",
    mainidx: 1,
    subidx: 0,
  },
  {
    userid: "cloudcoke",
    title: "Glass Menagerie, The",
    content: "vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor",
    nickname: "qkrwhdghks123",
    mainidx: 1,
    subidx: 0,
  },
  {
    userid: "web7722",
    title: "Plastic Age, The",
    content: "leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus",
    nickname: "qkrwhdghks123",
    mainidx: 2,
    subidx: 1,
  },
  {
    userid: "qkrwhdghks",
    title: "Gun the Man Down",
    content: "sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae",
    nickname: "cloud",
    mainidx: 2,
    subidx: 0,
  },
  {
    userid: "cloudcoke",
    title: "Makai Tensho: Samurai Reincarnation (Makai tenshô)",
    content: "ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam",
    nickname: "qkrwhdghks123",
    mainidx: 1,
    subidx: 0,
  },
  {
    userid: "web7722",
    title: "Asoka (Ashoka the Great)",
    content: "consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede",
    nickname: "qkrwhdghks123",
    mainidx: 0,
    subidx: 1,
  },
  {
    userid: "cloudcoke",
    title: "Maybe Baby",
    content: "dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius",
    nickname: "web",
    mainidx: 2,
    subidx: 1,
  },
  {
    userid: "cloudcoke",
    title: "Tattoo Nation",
    content: "duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis",
    nickname: "web",
    mainidx: 0,
    subidx: 1,
  },
  {
    userid: "qkrwhdghks",
    title: "My Sex Life... or How I Got Into an Argument (Comment je me suis disputé... (ma vie sexuelle))",
    content: "congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci",
    nickname: "web",
    mainidx: 1,
    subidx: 1,
  },
  {
    userid: "web7722",
    title: "'Round Midnight",
    content: "imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing",
    nickname: "qkrwhdghks123",
    mainidx: 2,
    subidx: 1,
  },
  {
    userid: "qkrwhdghks",
    title: "That Day, on the Beach (Hai tan de yi tian)",
    content: "sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue",
    nickname: "qkrwhdghks123",
    mainidx: 1,
    subidx: 1,
  },
  {
    userid: "cloudcoke",
    title: "Hunting Party, The",
    content: "eu felis fusce posuere felis sed lacus morbi sem mauris",
    nickname: "web",
    mainidx: 2,
    subidx: 0,
  },
  {
    userid: "cloudcoke",
    title: "Welcome to New York",
    content: "interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel",
    nickname: "web",
    mainidx: 2,
    subidx: 0,
  },
  {
    userid: "cloudcoke",
    title: "Buffalo Bill and the Indians, or Sitting Bull's History Lesson (a.k.a. Buffalo Bill and the Indians)",
    content: "eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis",
    nickname: "qkrwhdghks123",
    mainidx: 1,
    subidx: 1,
  },
  {
    userid: "web7722",
    title: "Captive (Cautiva) ",
    content: "porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet",
    nickname: "web",
    mainidx: 2,
    subidx: 1,
  },
  {
    userid: "qkrwhdghks",
    title: "The Strength of Water",
    content: "at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices",
    nickname: "web",
    mainidx: 0,
    subidx: 1,
  },
  {
    userid: "cloudcoke",
    title: "Batman & Mr. Freeze: Subzero",
    content: "lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id",
    nickname: "web",
    mainidx: 1,
    subidx: 1,
  },
  {
    userid: "qkrwhdghks",
    title: "Magic Camp",
    content: "tristique fusce congue diam id ornare imperdiet sapien urna pretium",
    nickname: "cloud",
    mainidx: 1,
    subidx: 1,
  },
  {
    userid: "web7722",
    title: "Fountain, The",
    content: "tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu",
    nickname: "cloud",
    mainidx: 2,
    subidx: 1,
  },
  {
    userid: "cloudcoke",
    title: "One Body Too Many",
    content: "quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida",
    nickname: "web",
    mainidx: 2,
    subidx: 1,
  },
  {
    userid: "web7722",
    title: "Now Where Did the Seventh Company Get to? (Mais où est donc passée la 7ème compagnie)",
    content: "a feugiat et eros vestibulum ac est lacinia nisi venenatis",
    nickname: "qkrwhdghks123",
    mainidx: 0,
    subidx: 0,
  },
  {
    userid: "qkrwhdghks",
    title: "Blind Husbands",
    content: "rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio",
    nickname: "cloud",
    mainidx: 0,
    subidx: 0,
  },
  {
    userid: "qkrwhdghks",
    title: "Nine Ways to Approach Helsinki (Yhdeksän tapaa lähestyä Helsinkiä)",
    content: "tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse",
    nickname: "cloud",
    mainidx: 1,
    subidx: 1,
  },
  {
    userid: "web7722",
    title: "Fever",
    content: "ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio",
    nickname: "qkrwhdghks123",
    mainidx: 1,
    subidx: 1,
  },
  {
    userid: "qkrwhdghks",
    title: "Snow White (Blancanieves)",
    content: "vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis",
    nickname: "cloud",
    mainidx: 2,
    subidx: 0,
  },
  {
    userid: "cloudcoke",
    title: "Only the Strong",
    content: "fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus",
    nickname: "qkrwhdghks123",
    mainidx: 1,
    subidx: 0,
  },
  {
    userid: "web7722",
    title: "Alive",
    content: "turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel",
    nickname: "cloud",
    mainidx: 1,
    subidx: 1,
  },
  {
    userid: "qkrwhdghks",
    title: "It's Alive",
    content: "rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis",
    nickname: "cloud",
    mainidx: 0,
    subidx: 0,
  },
  {
    userid: "cloudcoke",
    title: "Corridor, The (Koridorius)",
    content: "lectus pellentesque eget nunc donec quis orci eget orci vehicula",
    nickname: "web",
    mainidx: 1,
    subidx: 1,
  },
  {
    userid: "cloudcoke",
    title: "Matthew's Days",
    content: "nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat",
    nickname: "web",
    mainidx: 2,
    subidx: 0,
  },
  {
    userid: "web7722",
    title: "Dial 1119",
    content: "vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget",
    nickname: "cloud",
    mainidx: 0,
    subidx: 0,
  },
  {
    userid: "qkrwhdghks",
    title: "Redline",
    content: "eu orci mauris lacinia sapien quis libero nullam sit amet",
    nickname: "qkrwhdghks123",
    mainidx: 1,
    subidx: 1,
  },
  {
    userid: "web7722",
    title: "Täynnä Tarmoa",
    content: "ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis",
    nickname: "web",
    mainidx: 0,
    subidx: 1,
  },
  {
    userid: "qkrwhdghks",
    title: "Django the Bastard (Strangers Gundown, The) (Django il bastardo)",
    content: "sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in",
    nickname: "cloud",
    mainidx: 2,
    subidx: 0,
  },
  {
    userid: "qkrwhdghks",
    title: "End of Watch",
    content: "mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non",
    nickname: "web",
    mainidx: 1,
    subidx: 1,
  },
  {
    userid: "web7722",
    title: "How to Make Love to a Woman",
    content: "at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus",
    nickname: "qkrwhdghks123",
    mainidx: 2,
    subidx: 0,
  },
  {
    userid: "web7722",
    title: "Run of the Country, The",
    content: "sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam",
    nickname: "qkrwhdghks123",
    mainidx: 1,
    subidx: 0,
  },
  {
    userid: "cloudcoke",
    title: "Slap Shot",
    content: "molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst",
    nickname: "qkrwhdghks123",
    mainidx: 1,
    subidx: 0,
  },
  {
    userid: "web7722",
    title: "Illusionist, The (L'illusionniste)",
    content: "aliquet massa id lobortis convallis tortor risus dapibus augue vel",
    nickname: "cloud",
    mainidx: 0,
    subidx: 0,
  },
  {
    userid: "cloudcoke",
    title: "Bugsy",
    content: "erat volutpat in congue etiam justo etiam pretium iaculis justo",
    nickname: "web",
    mainidx: 1,
    subidx: 1,
  },
  {
    userid: "qkrwhdghks",
    title: "Captivated",
    content: "sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus",
    nickname: "qkrwhdghks123",
    mainidx: 0,
    subidx: 0,
  },
  {
    userid: "qkrwhdghks",
    title: "Bertie and Elizabeth",
    content: "quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi",
    nickname: "web",
    mainidx: 0,
    subidx: 1,
  },
  {
    userid: "qkrwhdghks",
    title: "Case of the Grinning Cat, The (Chats perchés)",
    content: "cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean",
    nickname: "web",
    mainidx: 2,
    subidx: 0,
  },
  {
    userid: "web7722",
    title: "Machine, The",
    content: "turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at",
    nickname: "web",
    mainidx: 2,
    subidx: 0,
  },
  {
    userid: "cloudcoke",
    title: "Bostonians, The",
    content: "hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat",
    nickname: "qkrwhdghks123",
    mainidx: 2,
    subidx: 1,
  },
  {
    userid: "web7722",
    title: "Men Who Tread on the Tiger's Tail, The (Tora no o wo fumu otokotachi)",
    content: "mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim",
    nickname: "qkrwhdghks123",
    mainidx: 0,
    subidx: 0,
  },
  {
    userid: "cloudcoke",
    title: "Human Lanterns (Ren pi deng long)",
    content: "vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra",
    nickname: "qkrwhdghks123",
    mainidx: 1,
    subidx: 1,
  },
  {
    userid: "cloudcoke",
    title: "King Creole",
    content: "lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer",
    nickname: "cloud",
    mainidx: 2,
    subidx: 0,
  },
  {
    userid: "web7722",
    title: "Find Love",
    content: "diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat",
    nickname: "cloud",
    mainidx: 1,
    subidx: 0,
  },
  {
    userid: "qkrwhdghks",
    title: "Attack of the Giant Leeches",
    content: "nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget",
    nickname: "qkrwhdghks123",
    mainidx: 1,
    subidx: 0,
  },
  {
    userid: "web7722",
    title: "The Red Inn",
    content: "porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in",
    nickname: "qkrwhdghks123",
    mainidx: 2,
    subidx: 1,
  },
  {
    userid: "cloudcoke",
    title: "Jingle All the Way",
    content: "luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus",
    nickname: "cloud",
    mainidx: 1,
    subidx: 0,
  },
  {
    userid: "qkrwhdghks",
    title: "Skins",
    content: "donec ut dolor morbi vel lectus in quam fringilla rhoncus",
    nickname: "qkrwhdghks123",
    mainidx: 1,
    subidx: 1,
  },
  {
    userid: "qkrwhdghks",
    title: "Dream Land",
    content: "ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis",
    nickname: "cloud",
    mainidx: 0,
    subidx: 1,
  },
  {
    userid: "web7722",
    title: "Bekas",
    content: "aliquam convallis nunc proin at turpis a pede posuere nonummy integer non",
    nickname: "web",
    mainidx: 1,
    subidx: 0,
  },
  {
    userid: "cloudcoke",
    title: "Message in a Bottle",
    content: "feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet",
    nickname: "cloud",
    mainidx: 2,
    subidx: 0,
  },
  {
    userid: "web7722",
    title: "Paint It Yellow (Rang De Basanti)",
    content: "pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales",
    nickname: "cloud",
    mainidx: 0,
    subidx: 1,
  },
  {
    userid: "cloudcoke",
    title: "Mahoney's Last Stand",
    content: "diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus",
    nickname: "qkrwhdghks123",
    mainidx: 0,
    subidx: 1,
  },
  {
    userid: "web7722",
    title: "Nick Fury: Agent of S.H.I.E.L.D.",
    content: "felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio",
    nickname: "web",
    mainidx: 2,
    subidx: 0,
  },
  {
    userid: "qkrwhdghks",
    title: "The Man Who Loved Yngve",
    content: "nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu",
    nickname: "qkrwhdghks123",
    mainidx: 2,
    subidx: 1,
  },
  {
    userid: "web7722",
    title: "Superman II",
    content: "vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum",
    nickname: "cloud",
    mainidx: 0,
    subidx: 1,
  },
  {
    userid: "qkrwhdghks",
    title: "Somersault",
    content: "posuere felis sed lacus morbi sem mauris laoreet ut rhoncus",
    nickname: "cloud",
    mainidx: 1,
    subidx: 1,
  },
  {
    userid: "cloudcoke",
    title: "We'll Never Have Paris",
    content: "diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi",
    nickname: "web",
    mainidx: 1,
    subidx: 1,
  },
  {
    userid: "web7722",
    title: "Red Dawn",
    content: "quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus",
    nickname: "cloud",
    mainidx: 2,
    subidx: 1,
  },
  {
    userid: "web7722",
    title: "Cazuza - O Tempo Não Pára",
    content: "aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan",
    nickname: "qkrwhdghks123",
    mainidx: 0,
    subidx: 0,
  },
  {
    userid: "web7722",
    title: "Wind Chill",
    content: "justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia",
    nickname: "cloud",
    mainidx: 2,
    subidx: 1,
  },
  {
    userid: "qkrwhdghks",
    title: "About Face: Supermodels Then and Now",
    content: "ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem",
    nickname: "qkrwhdghks123",
    mainidx: 1,
    subidx: 1,
  },
  {
    userid: "cloudcoke",
    title: "Mortal Kombat",
    content: "odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique",
    nickname: "cloud",
    mainidx: 2,
    subidx: 0,
  },
  {
    userid: "web7722",
    title: "The Woodcarver",
    content: "venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut",
    nickname: "cloud",
    mainidx: 0,
    subidx: 1,
  },
  {
    userid: "cloudcoke",
    title: "Animal Love (Tierische Liebe)",
    content: "interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien",
    nickname: "cloud",
    mainidx: 0,
    subidx: 1,
  },
  {
    userid: "cloudcoke",
    title: "April Fools, The",
    content: "ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse",
    nickname: "qkrwhdghks123",
    mainidx: 1,
    subidx: 0,
  },
  {
    userid: "qkrwhdghks",
    title: "The Tunnel of Love",
    content: "sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae",
    nickname: "web",
    mainidx: 0,
    subidx: 0,
  },
  {
    userid: "cloudcoke",
    title: "Route Irish",
    content: "proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis",
    nickname: "web",
    mainidx: 2,
    subidx: 0,
  },
  {
    userid: "qkrwhdghks",
    title: "Leopard, The (Gattopardo, Il)",
    content: "odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue",
    nickname: "web",
    mainidx: 0,
    subidx: 0,
  },
  {
    userid: "web7722",
    title: "Inspectors, The",
    content: "magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus",
    nickname: "web",
    mainidx: 1,
    subidx: 0,
  },
  {
    userid: "cloudcoke",
    title: "The Man Without a Map",
    content: "urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in",
    nickname: "cloud",
    mainidx: 1,
    subidx: 0,
  },
  {
    userid: "cloudcoke",
    title: "CQ",
    content: "eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam",
    nickname: "web",
    mainidx: 2,
    subidx: 0,
  },
  {
    userid: "qkrwhdghks",
    title: "Dernier Combat, Le (Last Battle, The)",
    content: "vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus",
    nickname: "cloud",
    mainidx: 2,
    subidx: 0,
  },
  {
    userid: "qkrwhdghks",
    title: "Barkleys of Broadway, The",
    content: "primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est",
    nickname: "web",
    mainidx: 1,
    subidx: 0,
  },
  {
    userid: "qkrwhdghks",
    title: "Return of the Living Dead 3",
    content: "orci eget orci vehicula condimentum curabitur in libero ut massa volutpat",
    nickname: "web",
    mainidx: 2,
    subidx: 0,
  },
  {
    userid: "web7722",
    title: "Crime of Passion",
    content: "in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in",
    nickname: "qkrwhdghks123",
    mainidx: 0,
    subidx: 1,
  },
  {
    userid: "qkrwhdghks",
    title: "Wood, The",
    content: "lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis",
    nickname: "qkrwhdghks123",
    mainidx: 2,
    subidx: 0,
  },
  {
    userid: "web7722",
    title: "Hi-Yo Silver",
    content: "pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit",
    nickname: "web",
    mainidx: 2,
    subidx: 1,
  },
  {
    userid: "qkrwhdghks",
    title: "Soldier of Fortune",
    content: "morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui",
    nickname: "cloud",
    mainidx: 2,
    subidx: 0,
  },
  {
    userid: "cloudcoke",
    title: "Senso",
    content: "odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor",
    nickname: "qkrwhdghks123",
    mainidx: 2,
    subidx: 0,
  },
  {
    userid: "web7722",
    title: "12:08 East of Bucharest (A fost sau n-a fost?)",
    content: "mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac",
    nickname: "web",
    mainidx: 1,
    subidx: 0,
  },
  {
    userid: "cloudcoke",
    title: "Class of Nuke 'Em High",
    content: "quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla",
    nickname: "web",
    mainidx: 1,
    subidx: 1,
  },
  {
    userid: "cloudcoke",
    title: "Baby Geniuses",
    content: "augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum",
    nickname: "web",
    mainidx: 1,
    subidx: 1,
  },
  {
    userid: "qkrwhdghks",
    title: "Tokyo Gore Police (Tôkyô zankoku keisatsu)",
    content: "elementum nullam varius nulla facilisi cras non velit nec nisi",
    nickname: "web",
    mainidx: 0,
    subidx: 1,
  },
  {
    userid: "web7722",
    title: "Midsummer Night's Sex Comedy, A",
    content: "ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo",
    nickname: "web",
    mainidx: 1,
    subidx: 0,
  },
  {
    userid: "qkrwhdghks",
    title: "Mask",
    content: "duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis",
    nickname: "web",
    mainidx: 0,
    subidx: 0,
  },
  {
    userid: "cloudcoke",
    title: "Bobo, The",
    content: "lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu",
    nickname: "cloud",
    mainidx: 2,
    subidx: 1,
  },
  {
    userid: "web7722",
    title: "31 North 62 East",
    content: "scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem",
    nickname: "web",
    mainidx: 2,
    subidx: 0,
  },
  {
    userid: "web7722",
    title: "You Were Never Lovelier",
    content: "velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante",
    nickname: "cloud",
    mainidx: 0,
    subidx: 0,
  },
  {
    userid: "qkrwhdghks",
    title: "Feet First",
    content: "velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus",
    nickname: "qkrwhdghks123",
    mainidx: 1,
    subidx: 1,
  },
  {
    userid: "web7722",
    title: "Bordertown",
    content: "sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel",
    nickname: "qkrwhdghks123",
    mainidx: 0,
    subidx: 0,
  },
  {
    userid: "cloudcoke",
    title: "Mahakaal (The Monster)",
    content: "integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper",
    nickname: "web",
    mainidx: 1,
    subidx: 0,
  },
];

module.exports = Boards;
